server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: web_ani
  datasource:
    url: jdbc:mysql://localhost:3306/momoyouta_web_ani
    username: root
    password: 'a102703407'
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password:  admin



